services:
  obeya:
    build: .
    container_name: planning-obeya
    ports:
      - "8501:8501"
    volumes:
      # Monter le dossier data pour persister la base de donn√©es
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - LANG=fr_FR.UTF-8
      - LC_ALL=fr_FR.UTF-8
      - LC_TIME=fr_FR.UTF-8
      - TZ=Europe/Paris
    restart: unless-stopped
